# Generated by Django 4.1.7 on 2023-03-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'NON IT'), ('Electronics', 'ETC')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
